### ISSUE TITLE
License mismatch

### ISSUE THREAD

**Issue by kuredoro** [stbrumme/hash-library#10]
The LICENSE file in the repository describes a Zlib license, but the license inside the actual source code is maximally restrictive. When the author reserves all rights, it means that *nobody* can use the code in any way, not for commercial use, not for personal. They can't modify it or redistribute.

Consider copy-pasting contents of LICENSE into all source files.

**Comment by stbrumme** [comment]
Files will only be modified in case of a bug or functional enhancements.
Legal stuff is none of those.
