### ISSUE TITLE
Keccak empty string hash value issue

### ISSUE THREAD

**Issue by zyluo** [stbrumme/hash-library#19]
Keccak sha3(Keccak::Keccak256);
std::cout << sha3("") << std::endl;

`expected: a7ffc6f8bf1ed76651c14756a061d662f580ff4de43b49fa82d80a4b80f8434a`
`actual  : c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470`

https://csrc.nist.gov/CSRC/media/Projects/Cryptographic-Standards-and-Guidelines/documents/examples/SHA3-256_Msg0.pdf

Let me know if I'm missing something.

**Comment by stbrumme** [comment]
Keccak isn't SHA3, even though they are _almost_ the same.
When using the dedicated SHA3 class, which is part of my repository, you get the expected output.
