### ISSUE TITLE
SHA3-512 bug

### ISSUE THREAD

**Issue by husrev** [stbrumme/hash-library#6]
Hexadecimal string `72a5f501151ca974002f34` returns the wrong hash value. Actually any string which starts with `72a5f501151ca974` returns a wrong hash. Maybe related to 64-bit data type?

**Comment by stbrumme** [comment]
I think the bug report is wrong, please check your code.

A minimal test program:
```
#include "../sha3.h"
#include <iostream>

int main(int argc, char *argv[])
{
  std::string text = "72a5f501151ca974002f34";

  SHA3 hasher(SHA3::Bits512);
  hasher.add(text.data(), text.size());
  std::cout << hasher.getHash() << std::endl;

  return 0;
}
```
it produces ```5372db30215cacc82bba9a6743f876a2aeee80df661bb9661a468b0c75d5c74cf21bae5f4df33c1f24e9b6c4f4409fa0f085a419f509938b636bf2a7011c9b68``` which is exactly the same hash I get with these three (random) SHA3-512 websites:
http://www.allencoders.online/hashers/sha3512/hash
https://emn178.github.io/online-tools/sha3_512.html
https://md5calc.com/hash/sha3-512/72a5f501151ca974002f34

**Comment by husrev** [comment]
This works. Probably the problem was my C-style string based input parser. Thanks.
