### ISSUE TITLE
Add hmac<SHA512>

### ISSUE THREAD

**Issue by fxfire** [stbrumme/hash-library#7]
Is there a way you could add the funcs in the SHA3 class, that would allow to use it with hmac ?

**Comment by stbrumme** [comment]
Using HMAC with SHA3 doesn't improve security (unlike SHA1 / SHA256).
Even though it's theoretical possible, there is no practical use.

By the way: my SHA3 implementation supports various hash sizes (224, 256, 384, 512).
However, the HMAC class needs a constant hash size. Therefore a SHA3-HMAC needs to be different code than the generic HMAC class for MD5/SHA1/SHA256. I don't think it's worth writing that class if it has only very limited practical use.

**Comment by fxfire** [comment]
Thank you for replying! Yes, I'm aware that there is no security gain, however, an API I recently wanted to use required a HMAC sha 512 and it is nearly impossible to find such lightweight code as yours which does that. After 3 hours of google and rewriting code, I managed to get it to work, but I can definitely tell you, that the only other solutions out there come with huge libraries (crypto++, openssl, poco etc.) So it might be a nice thing to add to your lovely small lib :)
