### ISSUE TITLE
No gethash(char[]) function in SHA3

### ISSUE THREAD

**Issue by archerian** [stbrumme/hash-library#8]
Hello, thanks for this library! I didnt see a getHash(unsigned char buffer[HashBytes]) function in SHA3, wasn't sure why. Can you please let me know? Thanks!

**Comment by stbrumme** [comment]
Hi,
all hash algorithms in my library have a fixed size, e.g. SHA1 produces 160 bits => 20 bytes.
The only exception is SHA3/Keccak which offers several hash lengths (224, 256, 384, 512) which can be chosen at runtime.
That means it's impossible to have a compile-time constant `HashBytes` - and therefore no `getHash(unsigned char buffer[HashBytes])`.
