### ISSUE TITLE
There is a memory leak

### ISSUE THREAD

**Issue by orbitcowboy** [stbrumme/hash-library#9]
There is a memory leak, please add `delete[] buffer;` to line 64 (before return)
https://github.com/stbrumme/hash-library/blob/f77b5646ca29bc4cfaa433996139d7d1c37cf650/digest.cpp#L60-L65
and the issue is fixed.
Best regards from the Cppcheck team ;-)

**Comment by stbrumme** [comment]
Thanks for reporting this issue.
Moreover, I added `-Wall -Wextra -pedantic` to the compiler's command-line. Now there are no warnings left.

The fixed code is on HEAD. No new tag was given because only test programs were affected, not the library itself.
